### ISSUE TITLE
Add dialog documentation to ui module

### ISSUE THREAD

**Issue by cosme12** [samyeyo/LuaRT-documentation#24]
I was checking the source code and found out there are a lot of `dialogs` methods that are not documented. Like `file` and `directory`. I think it will be really useful if we can have them at hand in the documentation.

**Comment by samyeyo** [comment]
Hi,
I don't know what you are referring to, but all the ui module functions relating to dialogs are well documented: ui.opendialog(), ui.dirdialog(), ui.savedialog(), ui.colordialog() and ui.fontdialog()

**Comment by cosme12** [comment]
> Hi,
> I don't know what you are referring to, but all the ui module functions relating to dialogs are well documented: ui.opendialog(), ui.dirdialog(), ui.savedialog(), ui.colordialog() and ui.fontdialog()

Oh, they are under the main page in the ui module. I searched each object looking for them and didn't realize there was more stuff in the main UI page.
