### ISSUE TITLE
Parameter headline standardisation

### ISSUE THREAD

**Issue by esferatec** [samyeyo/LuaRT-documentation#4]
There is a "Parameters" section in the documentation for the individual ui objects. Sometimes the headings of the parameters, which are optional, are written with [] and sometimes not. How should the standard procedure be?

**Comment by samyeyo** [comment]
Optional parameter should be surrounded by [ ]
If not, it's an error in the documentation

**Comment by esferatec** [comment]
OK, thank you. I will keep an eye on it if I find any other improvements to the documentation.
